### ISSUE TITLE
Please add handlebars to dependencies or Peerdependencies

### ISSUE THREAD

**Issue by AndyOGo** [ain/handlebars-helper-rawinclude#4]
Right now handlebars is listet in devDependencies.
But your module uses handlebars for production.

Please update you package.json to reflect this dependency correctly either with dependencies or peerDependencies.

I get this error:
> Error: Cannot find module 'handlebars'

**Comment by ain** [comment]
Thanks, good point. All dependencies are most likely also out of date, will make sure this gets sorted out for next release, which will probably be `0.1.0`.
